apiVersion: v1
kind: Service
metadata:
  name: aws-service
spec:
  selector:
    app: aws
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws
spec:
  selector:
    matchLabels:
      app: aws
  replicas: 4
  template:
    metadata:
      labels:
        app: aws
    spec:
      containers:
      - name: aws
        image: aws:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
