apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws
spec:
  selector:
    matchLabels:
      app: aws
  replicas: 4
  template:
    metadata:
      labels:
        app: aws
    spec:
      containers:
      - name: aws
        image: aws:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
